project_name: hostinger
version: 2

before:
  hooks:
    - mkdir -p completions
    - sh -c 'go run . completion bash > completions/hostinger.bash'
    - sh -c 'go run . completion zsh  > completions/hostinger.zsh'
    - sh -c 'go run . completion fish > completions/hostinger.fish'

builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -mod=vendor
      - -v
    ldflags:
      - -X github.com/hostinger/api-cli/utils.Build={{ .ShortCommit }}
      - -X github.com/hostinger/api-cli/utils.Major={{ .Major }}
      - -X github.com/hostinger/api-cli/utils.Minor={{ .Minor }}
      - -X github.com/hostinger/api-cli/utils.Patch={{ .Patch }}
    goos:
      - windows
      - darwin
      - linux

archives:
  - name_template: "hostinger-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - completions/*
    wrap_in_directory: false

source:
  enabled: true
  name_template: 'hostinger-{{ .Version }}-source'

checksum:
  name_template: "hostinger-{{ .Version }}-checksums.sha256"

#dockers:
#  - dockerfile: Dockerfile.goreleaser
#    image_templates:
#      - "hostinger/hostinger:latest"
#      - "hostinger/hostinger:{{ .Major }}-latest"
#      - "hostinger/hostinger:{{ .Version }}"

release:
  github:
    owner: hostinger
    name: api-cli

brews:
  - repository:
      owner: hostinger
      name: homebrew-tap
    directory: Formula
    homepage: "https://www.hostinger.com"
    description: "Hostinger API CLI"
    license: "MIT"
    install: |
      bin.install "hostinger"
    extra_install: |
      bash_completion.install "completions/hostinger.bash" => "hostinger"
      zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
      fish_completion.install "completions/hostinger.fish"

changelog:
  disable: false