package availability

import (
	"bytes"
	"context"
	"encoding/json"
	"log"

	"github.com/hostinger/api-cli/api"
	"github.com/hostinger/api-cli/output"
	"github.com/spf13/cobra"
)

var SuggestNamesFromDescriptionCmd = &cobra.Command{
	Use:   "suggest-names-from-description",
	Short: "Suggest domain names from a description",
	Long:  "Suggest available domain names based on a free-text description of your project.\n\nSuggestions are generated by an AI model, so they differ between calls.\n\nEndpoint has rate limit of 90 requests per minute.\n\nUse this endpoint to find a domain name when you only know what the website is about.",
	Run: func(cmd *cobra.Command, args []string) {
		payload, err := json.Marshal(suggestNamesFromDescriptionBody(cmd))
		if err != nil {
			log.Fatal(err)
		}
		r, err := api.Request().DomainsSuggestDomainNamesFromADescriptionV1WithBodyWithResponse(context.TODO(), "application/json", bytes.NewReader(payload))
		if err != nil {
			log.Fatal(err)
		}

		output.Format(cmd, r.Body, r.StatusCode())
	},
}

func init() {
	SuggestNamesFromDescriptionCmd.Flags().StringP("description", "", "", "Free-text description of the project the domain is needed for")
	SuggestNamesFromDescriptionCmd.Flags().IntP("limit", "", 0, "Amount of domain names to suggest")
	SuggestNamesFromDescriptionCmd.MarkFlagRequired("description")
	SuggestNamesFromDescriptionCmd.MarkFlagRequired("limit")
}

func suggestNamesFromDescriptionBody(cmd *cobra.Command) map[string]any {
	body := map[string]any{}
	descriptionVal, _ := cmd.Flags().GetString("description")
	body["description"] = descriptionVal
	limitVal, _ := cmd.Flags().GetInt("limit")
	body["limit"] = limitVal
	return body
}
