package availability

import (
	"bytes"
	"context"
	"encoding/json"
	"log"

	"github.com/hostinger/api-cli/api"
	"github.com/hostinger/api-cli/output"
	"github.com/spf13/cobra"
)

var SuggestNamesFromCmd = &cobra.Command{
	Use:   "suggest-names-from",
	Short: "Suggest domain names from a domain",
	Long:  "Suggest available domain names based on a domain name you already have in mind.\n\nSuggestions are generated by an AI model, so they differ between calls.\n\nEndpoint has rate limit of 90 requests per minute.\n\nUse this endpoint when the domain you wanted is taken and you need close alternatives.",
	Run: func(cmd *cobra.Command, args []string) {
		payload, err := json.Marshal(suggestNamesFromBody(cmd))
		if err != nil {
			log.Fatal(err)
		}
		r, err := api.Request().DomainsSuggestDomainNamesFromADomainV1WithBodyWithResponse(context.TODO(), "application/json", bytes.NewReader(payload))
		if err != nil {
			log.Fatal(err)
		}

		output.Format(cmd, r.Body, r.StatusCode())
	},
}

func init() {
	SuggestNamesFromCmd.Flags().StringP("domain", "", "", "Domain name to base the suggestions on")
	SuggestNamesFromCmd.Flags().IntP("limit", "", 0, "Amount of domain names to suggest")
	SuggestNamesFromCmd.MarkFlagRequired("domain")
	SuggestNamesFromCmd.MarkFlagRequired("limit")
}

func suggestNamesFromBody(cmd *cobra.Command) map[string]any {
	body := map[string]any{}
	domainVal, _ := cmd.Flags().GetString("domain")
	body["domain"] = domainVal
	limitVal, _ := cmd.Flags().GetInt("limit")
	body["limit"] = limitVal
	return body
}
